ConvertFrom-StringData @'
 FileSystemPathRequired=The path should be on the FileSystem : {0}
 FileSystemPathRequiredForCurrentLocation=The use of relative path, requires that the current path must to be on the file system : {0}
 GlobbingUnsupported=The globbing is not supported for this parameter : {0} 
 ParameterMustBeAfile=The parameter must be a file name and not a directory name : {0}
 ParameterMustBeAdirectory=The parameter must be a directory name and not a file name : {0}
 DriveNotFound=The specified drive does not exist : '{0}'  
 ItemNotFound=The file does not exist : '{0}'
 PathNotFound=The directory does not exist : '{0}'  
 
 BeginAnalyze=Startup of the file analysis '{0}'
 InitializeComponentNotFound=The InitializeComponent () method is not found in the file '{0}'. The conversion can not be performed.
 
 DesignerNameNotFound=Verify that the name of the source file is the one generated by the Visual Studio designer.
 FormNameNotFound=The name of the Form is not found in the InitializeComponent () method of the file '{0}'. The conversion cannot be done. {1}  
 TransformationProgress=Transformation of source code ({0}) lines
 TransformationProgressStatus=Please wait
 ReadChoiceCaption=The destination file already exists : '{0}'
 ReadChoiceMessage=Do you want to replace it ?
 OperationCancelled=Operation aborted.
 
 GenerateScript=Script generation '{0}'
 SyntaxVerification=Syntax check of the generated script.
 SyntaxError=The syntax of the generated script contains errors. For detailed errors, run: Test-PSScript '{0}'
 
 ConversionComplete=Conversion is complete : '{0}' 
 
 ParameterIsExclusif=Use either the parameter 'Destination' or the parameter 'DestinationLiteral', but not both simultaneously.
 ParameterIsNotAllow=The parameter 'Secondary' indicates the conversion of a secondary form, the parameter 'HideConsole' can not be used that at a conversion of a primary form.
 AddSTARequirement=Adding the control of STA thread model. Reason: {0}

 LoadingAssemblies=# Loading external assemblies
 DisposeResources=# Release of resources
 DisposeForm=# Release the Form 
'@ 

